config/routes.rb
Rails.application.routes.draw do
  resources :agencies do
    resources :properties
  end

  get 'search', to: 'search#search'

  root to: 'agencies#index'
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :property, dependent: :destroy
  validates :address, :presence => true
end

app/models/agency.rb
class Agency < ActiveRecord::Base
  has_many :properties, dependent: :destroy
  validates :title, :presence => true

end

app/models/property.rb
require 'elasticsearch/model'

class Property < ActiveRecord::Base
  belongs_to :agency
  has_one :address

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  enum property_type: [ :residential, :rental, :commercial ]

  validates :title, :presence => true
  validates :city, :presence => true
  validates :property_type, :presence => true, inclusion: { in: Property.property_types.keys }
  validates :price, :presence => true, numericality: { greater_than_or_equal_to: 0 }
end

Property.import # for auto sync model with elastic search

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  def index
    @agencies = Agency.paginate(:page => params[:page]).order("created_at ASC")
  end
end

app/controllers/agency_controller.rb
class AgencyController < ApplicationController
  def index
    @agencies = Agency.order("created_at DESC").limit(5)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  WillPaginate.per_page = 5
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    @agency = Agency.find(params[:agency_id])
    @properties = @agency.properties.paginate(:page => params[:page]).order("created_at DESC")
  end

  def show
    @property = Property.find(params[:id])
    console
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:q].nil?
      @properties = []
    else
      @search_params = {}
      if params[:city].present?
        @search_params.merge!({
            city: params[:city]
        })
      end
      if params[:property_type].present?
        @search_params.merge!({
          property_type: params[:property_type]
        })
      end

      @properties = Property.search(params[:q]).records.where(@search_params)
      @results_found = @properties.count

    end
  end
end

app/helpers/agency_helper.rb
module AgencyHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/property_helper.rb
module PropertyHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/agencies/index.html.erb
<h3>Agency Listing</h3>
<div class="well main">
  <% if @agencies.blank? %>
    <span class = "text-danger">No agencies found!</span>
  <% else %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
        </tr>
      </thead>
      <tbody>
        <% @agencies.each do |a| %>
          <tr>
            <td>
              <%= link_to(a.title, agency_properties_path(a)) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @agencies, renderer: BootstrapPagination::Rails %>
  <% end %>
</div>

app/views/agency/index.html.erb
<h2>Agency Listing</h2>
<div class="well main">
  <% if @agencies.blank? %>
    <span class = "text-danger">No agencies found!</span>
  <% else %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
        </tr>
      </thead>
      <tbody>
          <% @agencies.each do |a| %>
          <tr>
            <td>
              <%= link_to(a.title, "#") %>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PropertiesTest" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <a class="navbar-brand" href="/"><strong>Property Listing App</strong></a>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= render 'shared/search_bar' %>
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Sumon SM 2016</p>
      </footer>
    </div> <!-- /container -->

  </body>
</html>

app/views/properties/index.html.erb
<h3>Properties for <strong><%= @agency.title %></strong></h3>
<div class="well main">
  <% if @properties.blank? %>
    <span class = "text-danger">No properties found!</span>
  <% else %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>City</th>
          <th>Address</th>
          <th>Property Type</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% @properties.each do |p| %>
          <tr>
            <td>
              <%= link_to(p.title, agency_property_path(@agency.id, p.id)) %>
            </td>
            <td>
              <%= p.city %>
            </td>
            <td>
              <%= p.address.address %>
            </td>
            <td>
              <%= p.property_type %>
            </td>
            <td>
              <%= p.price %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @agencies, renderer: BootstrapPagination::Rails %>
  <% end %>
</div>

app/views/properties/show.html.erb
<h3 class="text-uppercase"><%= @property.address.address %></h3>
<dl class="dl-horizontal well">
  <dt>Title:</dt><dd><%= @property.title %></dd>
  <dt>Price:</dt><dd><%= @property.price %></dd>
  <dt>Property Type:</dt><dd><%= @property.property_type %></dd>
  <dt>City:</dt><dd><%= @property.city %></dd>
  <dt>Description:</dt><dd><%= @property.description %></dd>
</dl>

app/views/search/search.html.erb
<h3>Search results for <strong><%= params[:q] %></strong></h3>
<%= console %>
<div class="well main">
  <% if @properties.blank? %>
    <span class="text-danger">No properties found! Try different search terms.</span>
  <% else %>
    <span class="text-info"><strong><%= @results_found %></strong> Total properties found</span>
    <div>
        <div>city: <%= params[:city] %></div>
        <div>type: <%= params[:property_type] %></div>
    </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>City</th>
          <th>Address</th>
          <th>Property Type</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% @properties.each do |p| %>
          <tr>
            <td>
              <%= link_to(p.title, agency_property_path(p.agency.id, p.id)) %>
            </td>
            <td>
              <%= p.city %>
            </td>
            <td>
              <%= p.address.address %>
            </td>
            <td>
              <%= p.property_type %>
            </td>
            <td>
              <%= p.price %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/shared/_search_bar.html.erb
<form action="/search" method="get" class="form-horizontal" role="form">

<div class="input-group" id="adv-search">
      <input type="text" name="q" class="form-control" placeholder="Search for properties" />
      <div class="input-group-btn">
          <div class="btn-group" role="group">
              <div class="dropdown dropdown-lg">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></button>
                  <div class="dropdown-menu dropdown-menu-right" role="menu">

                        <div class="form-group">
                          <label for="filter">Filter by</label>
                          <select class="form-control" name="property_type">
                              <option value="" selected>Any Types</option>
                              <option value="0">Residential</option>
                              <option value="1">Rental</option>
                              <option value="2">Commercial</option>
                          </select>
                        </div>
                        <div class="form-group">
                          <label for="contain">City</label>
                          <input class="form-control" name="city" type="text" />
                        </div>

                  </div>
              </div>
              <button type="submit" class="btn btn-primary"">Search</button>
          </div>
      </div>
  </div>
</form>